version: "3.8"

services:
  db:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3333:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Catelaso26
    networks:
      - java_network
  java_docker:
    container_name: java_docker
    image: java_docker:1.0
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - java_network
networks:
  java_network:
    name: java_network
